/**
 * Typed loaders for the normalized entity JSON produced by the data pipeline.
 *
 * Reads from data/processed/ (generated by `npm run process`, git-ignored,
 * regenerated fresh in CI). Falls back to the committed data/seed/ snapshot so
 * `npm run dev` works offline without first running the pipeline.
 */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type { Club, League, Match } from "./types.ts";

const PROCESSED_DIR = join(process.cwd(), "data", "processed");
const SEED_DIR = join(process.cwd(), "data", "seed");

const cache = new Map<string, unknown>();

function loadJson<T>(name: string): T {
  if (cache.has(name)) return cache.get(name) as T;

  const processed = join(PROCESSED_DIR, name);
  const seed = join(SEED_DIR, name);
  const path = existsSync(processed) ? processed : seed;

  if (!existsSync(path)) {
    throw new Error(
      `Missing data file "${name}". Run \`npm run data\` to fetch + process, ` +
        `or commit a seed snapshot to data/seed/.`,
    );
  }

  const data = JSON.parse(readFileSync(path, "utf8")) as T;
  cache.set(name, data);
  return data;
}

export function getLeagues(): League[] {
  return loadJson<League[]>("leagues.json");
}

export function getClubs(): Club[] {
  return loadJson<Club[]>("clubs.json");
}

export function getMatches(): Match[] {
  return loadJson<Match[]>("matches.json");
}

export function getMatch(id: string): Match | undefined {
  return getMatches().find((m) => m.id === id);
}

export function getLeague(slug: string): League | undefined {
  return getLeagues().find((l) => l.slug === slug);
}

export function getClub(idOrSlug: string): Club | undefined {
  return getClubs().find((c) => c.slug === idOrSlug || c.id === idOrSlug);
}

export function getClubsByLeague(leagueId: string): Club[] {
  return getClubs().filter((c) => c.league_ids.includes(leagueId));
}

export function getMatchesByLeagueSeason(
  leagueId: string,
  season: string,
): Match[] {
  return getMatches().filter(
    (m) => m.league_id === leagueId && m.season === season,
  );
}
